/* Generated by Together */

package ontorama.webkbtools.query.parser;



import java.util.Iterator;

import java.io.Reader;



public interface Parser {

    /**

     * get an Iterator of OntologyTypes from the given stream

     * @param	reader

     * @return	Iterator of OntologyTypes

     */

    public Iterator getOntologyTypeIterator (Reader reader);


}

