/* Generated by Together */
package ontorama.webkbtools.query.parser;

import java.util.Iterator;
import java.io.InputStream;

public interface Parser {
    /**
     * get an Iterator of OntologyTypes from the given stream
     * @param	inputDataStream
     * @return	Iterator of OntologyTypes
     */
    public Iterator getOntologyTypeIterator (InputStream inputDataStream);
}
