package ontorama.webkbtools.query;

/* Generated by Together */

import ontorama.OntoramaConfig;
import ontorama.webkbtools.query.parser.Parser;

abstract public class TypeQueryBase implements TypeQuery {

  public String queryParamTerm = null;
  public String queryParamLink = null;
  public String queryParamDestTerm = null;
  public String queryParamResursLink = null;
  public String queryParamDepth = null;
  public String queryParamCreator = null;
  public String queryParamNonCreator = null;
  public String queryParamHyperlinks = null;

  public String queryUrl;
  public String queryOutputFormat;
  public Parser parser;

  public TypeQueryBase (){
    this.queryUrl = OntoramaConfig.queryUrl;
    this.queryOutputFormat = OntoramaConfig.queryOutputFormat;
    // TODO: more thought required for error handling
    try {
      parser = (Parser) (Class.forName(OntoramaConfig.parserPackageName).newInstance());
    }
    catch (Exception e) {
      System.out.println("Exception: " + e);
      System.exit(-1);
    }
  }

}
