/* Generated by Together */

package ontorama.webkbtools.query;

import java.io.InputStream;
import java.io.DataInputStream;
import java.util.Iterator;

import ontorama.webkbtools.query.parser.Parser;

public class TypeQueryImplementation extends TypeQueryBase {

    public TypeQueryImplementation () {
        super();
    }

    public Iterator getTypeRelative(String termName) {
        parser.getOntologyTypeIterator(new DataInputStream(System.in));
        //parser.toString();
        return null;
    }

    public Iterator getTypeRelative(String termName, int relationLink) {
        return null;
    }

    public String toString() {
        return ("queryUrl = " + queryUrl +
            	", queryOutputFormat = " + queryOutputFormat);
    }
}
