/* Generated by Together */

package ontorama;

public class OntoramaConfig {
    /**
     * Ontology Server Url for searching types
     */
    public static String queryUrl;
    /**
     * Specify Ontology Server Output format
     */
    public static String queryOutputFormat;
    /**
     * Specify Parser to use with queryOutputFormat.
     * All parsers should have ontorama.webkbtools.query.parser as root
     * and implement Parser iterface.
     */
    public static String parserPackageName;

    /**
     * where to find parser
     */
    private static final String parserPackagePathPrefix = "ontorama.webkbtools.query.parser";

    /**
     * All predefined relationLinks constants
     */
	public static final int SUPERTYPE = 0;
	public static final int SUBTYPE = 1;
	public static final int PARTOF = 2;
	public static final int HASAPART = 3;
	public static final int MEMBEROF = 4;
	public static final int HASAMEMBER = 5;
	public static final int SYNONYMTYPE = 6;
	public static final int INSTANCEOF = 7;
	public static final int HASAINSTANCE = 8;
	public static final int SUBSTANCEOF = 9;
	public static final int HASASUBSTANCE = 10;
	public static final int INCLUSIVETYPE =11;
	public static final int EXCLUSIVETYPE = 12;

	public static final int MAXTYPELINK = 12;

	static {
        queryUrl = "http://meganesia.int.gu.edu.au/~phmartin/WebKB/bin/termSearch.cgi";
        queryOutputFormat = "RDF";
        parserPackageName = parserPackagePathPrefix + "." + "rdf.RdfParser";
    }
}
