/* Generated by Together */

package ontorama.webkbtools.query.parser.rdf;

import ontorama.webkbtools.query.parser.Parser;

import java.util.Iterator;
import java.io.InputStream;

public class RdfParser implements Parser {

    public Iterator getOntologyTypeIterator (InputStream inputDataStream) {
        return null;
    }
}
